### ISSUE TITLE
Creative Alchemy Restriction Remover

### ISSUE THREAD

**Issue by EAXeffects** [Choum28/NewAlchemy#1]
Hi Choum28,

Recently I discovered a modification for Creative ALchemy called Creative ALchemy Restriction Remover. It has the ability to run CA on any PC - even ones with no sound card at all. This has allowed me to run old PC games on laptops with no way to install a sound card and emulate all of their old EAX sound effects. 

The only problem is that CA and CARR have no customization settings of any kind, and the EAX effects emulated by CARR are extremely quiet. Specifically, I would like to be able to increase the volume of 3D and environmental sound effects for games like Diablo 2, without having to increase the volume of all other sound effects simultaneously.

Do you know if volume customization for EAX effects specifically is something that NewAlchemy can do, or is something that you might be interested in making it do? Does the ability of CARR to emulate a sound card interest you?

Let me know how things are going for you, and thank you for your time.

**Comment by Choum28** [comment]
Hi,

For the EAX Volume slider, I know that old sound card like X-fi was having a specific EAX tab in their control panel to control EAXvolume (personnaly I never used it). Now I use an AE-7 and all settings related to EAX are gone, as EAX is depreciated for creative.

Concernig New alchemy, this is just a replacement for the alchemy.exe program that only copy remove the wrapper from game folder and set the wrapper ini, it will not change in any way the wrapper itself (Dsound.dll).

Perhaps you should try DSOAL, which is another wrapper build from scratch than convert directsound 3D and EAX to openAL, DSOAL only fully support EAX 2 and have partial support for other EAX (Diablo 2 is using EAX2).

**Comment by EAXeffects** [comment]
Thank you for your help, I am working this weekend, I will get back to you in several days. Sounds promising!

**Comment by Choum28** [comment]
closed as this is not directly related to an issue with the project.
